"""baseline schema

Revision ID: 27bdb0d866dd
Revises: 
Create Date: 2026-05-11 09:00:36.149377+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bdb0d866dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('venue_type', sa.String(length=100), nullable=True),
    sa.Column('event_category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('restaurant_share_token', sa.String(length=64), nullable=True),
    sa.Column('seating_share_token', sa.String(length=64), nullable=True),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_public_token'), 'events', ['public_token'], unique=True)
    op.create_index(op.f('ix_events_restaurant_share_token'), 'events', ['restaurant_share_token'], unique=True)
    op.create_index(op.f('ix_events_seating_share_token'), 'events', ['seating_share_token'], unique=True)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_reminders', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('include_google_maps_link', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dietary_requirements', sa.Text(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('rsvp_status', sa.String(length=20), nullable=False),
    sa.Column('google_form_response_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendees_id'), 'attendees', ['id'], unique=False)
    op.create_table('custom_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_forms_id'), 'custom_forms', ['id'], unique=False)
    op.create_index(op.f('ix_custom_forms_share_token'), 'custom_forms', ['share_token'], unique=True)
    op.create_table('google_form_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=255), nullable=False),
    sa.Column('form_title', sa.String(length=255), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_form_connections_id'), 'google_form_connections', ['id'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('venue_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requires_seating', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('assign_notes', sa.Text(), nullable=True),
    sa.Column('meal_options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_items_id'), 'schedule_items', ['id'], unique=False)
    op.create_table('seating_arrangements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seating_arrangements_id'), 'seating_arrangements', ['id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.create_table('form_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['custom_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_invitations_id'), 'form_invitations', ['id'], unique=False)
    op.create_table('seat_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrangement_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['seating_arrangements.id'], ),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_assignments_id'), 'seat_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_assignments_id'), table_name='seat_assignments')
    op.drop_table('seat_assignments')
    op.drop_index(op.f('ix_form_invitations_id'), table_name='form_invitations')
    op.drop_table('form_invitations')
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_seating_arrangements_id'), table_name='seating_arrangements')
    op.drop_table('seating_arrangements')
    op.drop_index(op.f('ix_schedule_items_id'), table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index(op.f('ix_google_form_connections_id'), table_name='google_form_connections')
    op.drop_table('google_form_connections')
    op.drop_index(op.f('ix_custom_forms_share_token'), table_name='custom_forms')
    op.drop_index(op.f('ix_custom_forms_id'), table_name='custom_forms')
    op.drop_table('custom_forms')
    op.drop_index(op.f('ix_attendees_id'), table_name='attendees')
    op.drop_table('attendees')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_events_seating_share_token'), table_name='events')
    op.drop_index(op.f('ix_events_restaurant_share_token'), table_name='events')
    op.drop_index(op.f('ix_events_public_token'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
